Works

diff --git a/baj-lib.yml b/baj-lib.yml
--- a/baj-lib.yml
+++ b/baj-lib.yml
@@ -4,6 +4,11 @@
 - id: [ loop, args, map ]
   is: [ fa ]
 
+- id: [ txt1, nss1, fn1, listid1, fn1, def1, ids1, forget1, lib1, exp1, warn, optal ]
+  is: [ na ]
+
+- { ky: [ tt ], is: [ nv ] }
+
 - id: opts
   sh: |-
     # Use «local -A opts; local args cont; opts "$@"» in caller
@@ -24,8 +29,14 @@
             *) args+=("$1"); shift;;
         esac
     done; cont=("$@")
+  tt: |
+    local -A opts; local args cont; opts "$@"
 
 - m4:
+    NS: |-
+      ${FUNCNAME%%:*}
+    ID: |-
+      ${FUNCNAME#*:}
     SELF: |-
       jq "$jq" $@
     OPTS: |-
@@ -39,7 +50,7 @@
 
 - { id: self, sh: jq "$jq" "$@" }
 - { id: tst, sh: '< ${1:?}' }
-- { id: txt, sh: 'loop $ns:tst "$@" && cat "$@" | txt1' }
+- { id: txt, sh: 'loop tst "$@" && cat "$@" | txt1' }
 - { id: txt1, sh: 'header; asjs | bm4 | dist | emit' }
 
 - { id: nss, sh: 'loop nss1 "$@"' }
@@ -72,22 +83,23 @@
 - { id: forget, sh: 'loop forget1 "$@"' }
 - id: forget1
   sh: |-
-    . <($ns:listid1 ${1:?} | args echo unset -f; nsp $1 && { aliases $1 | args echo unalias; echo unalias $1; })
+    . <(NS:listid1 ${1:?} | args echo unset -f; nsp $1 && { aliases $1 | args echo unalias; echo unalias $1; })
 
-- { id: load, sh: forget $(nss "$@"); . <($ns:txt "$@") }
+- { id: load, sh: forget $(nss "$@"); . <(NS:txt "$@") }
 
-- { id: warn, sh: 'echo \# generated by $ns:${FUNCNAME[1]}, avoid edit' }
+- { id: warn, sh: 'echo \# generated by ${FUNCNAME[1]}, avoid edit' }
 - { id: optal, sh: echo shopt -s expand_aliases }
 - { id: prudent, sh: echo set -euo pipefail; echo shopt -s inherit_errexit }
 
-- { id: exp, sh: 'listid ${1:?} | args echo export -f' }
+- { id: exp1, sh: 'listid ${1:?} | args echo export -f' }
+- { id: exp, sh: loop exp1 "$@" }
 
 - { id: lib1, sh: 'nsp ${1:?} || fail not a ns; alias $1; alias $(aliases $1); fn $1' }
 - { id: lib, sh: optal; loop lib1 "$@"; def self; exp "$@" }
 
 - id: with-lib
   sh: >-
-    (($#)) || fail $id; optal;
+    (($#)) || fail; optal;
     until [[ $# == 0 || $1 == -- ]]; do lib1 $1; shift; done;
     [[ $1 == -- ]] && shift; def self;
     (($#)) && { f=${BASH_ALIASES[$1]:-$1}; shift; echo $f "${@@Q}"; }
